# Generated by Django 3.2.8 on 2021-10-08 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicativo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teste',
            name='idade',
        ),
    ]
